package com.jel.handgesture

/** 제스처가 실행할 동작 */
enum class GestureAction(val label: String) {
    NONE("없음"),
    SWIPE_UP("위로 쓸기 · 아래 내용 보기"),
    SWIPE_DOWN("아래로 쓸기 · 위 내용 보기"),
    FLING_UP("위로 튕기기 · 크게 스크롤"),
    FLING_DOWN("아래로 튕기기 · 크게 스크롤"),
    SWIPE_LEFT("왼쪽으로 넘기기 · 다음"),
    SWIPE_RIGHT("오른쪽으로 넘기기 · 이전"),
    BACK("뒤로 가기"),
    HOME("홈"),
    RECENTS("최근 앱"),
    LAST_APP("이전 앱으로 전환"),
    ALL_APPS("앱 서랍"),
    NOTIFICATIONS("알림창 열기"),
    QUICK_SETTINGS("제어센터 (빠른 설정)"),
    CLOSE_SHADE("알림창·제어센터 닫기"),
    SCREENSHOT("스크린샷"),
    LOCK("화면 잠금"),
    POWER_MENU("전원 메뉴"),
    SPLIT_SCREEN("분할 화면"),
    MEDIA_PLAY_PAUSE("음악 재생/일시정지"),
    MEDIA_NEXT("다음 곡"),
    MEDIA_PREV("이전 곡"),
    VOLUME_UP("볼륨 올리기"),
    VOLUME_DOWN("볼륨 내리기"),
    POINTER_MODE("포인터 모드 켜기/끄기"),
}

/** 인식하는 제스처와 기본 동작 */
enum class Trigger(val group: String, val label: String, val short: String, val default: GestureAction) {
    PALM_UP("🖐 손바닥 휘두르기", "위로 ↑", "🖐↑", GestureAction.SWIPE_UP),
    PALM_DOWN("🖐 손바닥 휘두르기", "아래로 ↓", "🖐↓", GestureAction.SWIPE_DOWN),
    PALM_LEFT("🖐 손바닥 휘두르기", "왼쪽으로 ←", "🖐←", GestureAction.SWIPE_LEFT),
    PALM_RIGHT("🖐 손바닥 휘두르기", "오른쪽으로 →", "🖐→", GestureAction.BACK),
    PALM_PUSH("🖐 손바닥 밀기·당기기", "카메라 쪽으로 밀기", "🖐 밀기", GestureAction.MEDIA_PLAY_PAUSE),
    PALM_PULL("🖐 손바닥 밀기·당기기", "몸 쪽으로 당기기", "🖐 당기기", GestureAction.NONE),
    INDEX_UP("☝ 검지 휘두르기", "위로 ↑", "☝↑", GestureAction.SWIPE_UP),
    INDEX_DOWN("☝ 검지 휘두르기", "아래로 ↓", "☝↓", GestureAction.SWIPE_DOWN),
    INDEX_LEFT("☝ 검지 휘두르기", "왼쪽으로 ←", "☝←", GestureAction.SWIPE_LEFT),
    INDEX_RIGHT("☝ 검지 휘두르기", "오른쪽으로 →", "☝→", GestureAction.BACK),
    V_UP("✌ 두 손가락 휘두르기", "위로 ↑", "✌↑", GestureAction.CLOSE_SHADE),
    V_DOWN("✌ 두 손가락 휘두르기", "아래로 ↓", "✌↓", GestureAction.NOTIFICATIONS),
    V_LEFT("✌ 두 손가락 휘두르기", "왼쪽으로 ←", "✌←", GestureAction.LAST_APP),
    V_RIGHT("✌ 두 손가락 휘두르기", "오른쪽으로 →", "✌→", GestureAction.RECENTS),
    THREE_UP("🤟 세 손가락 휘두르기", "위로 ↑", "3손가락↑", GestureAction.HOME),
    THREE_DOWN("🤟 세 손가락 휘두르기", "아래로 ↓", "3손가락↓", GestureAction.QUICK_SETTINGS),
    THREE_LEFT("🤟 세 손가락 휘두르기", "왼쪽으로 ←", "3손가락←", GestureAction.MEDIA_PREV),
    THREE_RIGHT("🤟 세 손가락 휘두르기", "오른쪽으로 →", "3손가락→", GestureAction.MEDIA_NEXT),
    THUMB_UP("✊ 손 모양 멈춰서 유지", "👍 엄지 위", "👍", GestureAction.HOME),
    THUMB_DOWN("✊ 손 모양 멈춰서 유지", "👎 엄지 아래", "👎", GestureAction.BACK),
    SHAKA("✊ 손 모양 멈춰서 유지", "🤙 엄지+새끼", "🤙", GestureAction.RECENTS),
    OK("✊ 손 모양 멈춰서 유지", "👌 OK", "👌", GestureAction.SCREENSHOT),
    FIST("✊ 손 모양 멈춰서 유지", "✊ 주먹", "✊", GestureAction.POINTER_MODE),
    ROCK("✊ 손 모양 멈춰서 유지", "🤘 검지+새끼", "🤘", GestureAction.NONE),
    LOVE("✊ 손 모양 멈춰서 유지", "🤟 엄지+검지+새끼", "🤟", GestureAction.NONE),
    GUN("✊ 손 모양 멈춰서 유지", "L자 (엄지+검지)", "L", GestureAction.NONE),
}
